apiVersion: apps/v1
kind: Deployment
metadata:
  name: dana-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dana-mongodb
  template:
    metadata:
      labels:
        app: dana-mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:6
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: dana-mongodb
spec:
  selector:
    app: dana-mongodb
  ports:
    - port: 27017
      targetPort: 27017